loginemail="xpath://input[@class='_2IX_2- VJZDxU']"
loginpassword="//input[@class='_2IX_2- _3mctLh VJZDxU']"
loginbutton="xpath://button[@class='_2KpZ6l _2HKlqd _3AWRsL']"
xmark="xpath://button[@class='_2KpZ6l _2doB4z']"
searchbox="xpath://input[@title='Search for products, brands and more']"
searchbutton="xpath://button[@type='submit']"
product="xpath:/html/body/div[1]/div/div[3]/div[1]/div[2]/div[2]/div/div/div/a/div[2]/div[1]/div[1]"
productprice="xapth://div[@class='_30jeq3 _16Jk6d']"
pincode="xpath://input[@placeholder='Enter Delivery Pincode']"
pincodecheck="xpath://span[text()='Check']"
buynow="xpath://li[@class='col col-6-12'][2]"
