company = "xpath://span[@class='currentLanguage']"
features = "xpath://span[text()='Features']"
product = "xpath://span[text()='Product']"
carmodule = "xpath://a[@href='https://phptravels.com/cars-module-features/']"
overview_demo = "xpath://a[@class='btn btn-lp-primary background-white btn-l mt-3 mr-0 mr-md-3']"
phptravels  = "xpath://small[text()='http://www.phptravels.net']"
loign = "xpath://a[@class='lvl-0 sign-in btn btn-md btn-white-outline']"
account=    "xpath://*[@id='Secondary_Navbar-Account']/a"
registernewuser= "xpath://li[@menuitemname='Account']//ul//li[2]"
register= "xpath://input[@value='Register']"
firstname= "xpath://input[@name='firstname']"